name : Build and deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'BibliotecaAPI/**'
      - 'BibliotecaAPITests/**'
      - '.github/workflows/compile-deploy.yml'

env:
  VERSION_DOTNET: '9'
 # AZURE_APP_SERVICE_NOMBRE: BibliotecaAPI2025
 # AZURE_APP_SERVICE_UBICACION_PAQUETE: '.'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      proyecto: BibliotecaAPI/BibliotecaAPI.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
           dotnet-version: ${{ env.VERSION_DOTNET }}

      - name: Get Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Tests
        run: dotnet test --no-build

    #  - name: Publish
     #   run: dotnet publish $proyecto -c Release -o miapp --runtime win-x86

     # - name: Load Artifact
      #  uses: actions/upload-artifact@v4.6.2
       # with:
        #  path: ./miapp
         # name: build

# deploy:
#  permissions:
 #   content: none
  #runs-on: ubuntu-latest
  #needs: build
  #steps:
  #  - name: Get Artifacts
   #   uses: actions/download-artifact@v4.3.0
    #  with:
     #   name: build

    #- name: Deploy to Azure App Service    
     # uses: Azure/webapps-deploy@v2
     # with:
      #  app-name: $ {{ env.AZURE_APP_SERVICE_NOMBRE }}
       # publish-profile: ${{ secrets.AZURE_PERFIL_PUBLICO }}
        #package: ${{ env.AZURE_APP_SERVICE_UBICACION_PAQUETE }}
